name = "RoboDojo"
uuid = "2859eb88-988f-4613-a49e-c643bedbc906"
authors = ["thowell <thowell@stanford.edu>", "simon-lc <simonlc@stanford.edu>"]
version = "0.1.1"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
CoordinateTransformations = "150eb455-5306-5404-9cee-2592286d6298"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MeshCat = "283c5d60-a78f-5afe-a0af-af636b173e11"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
Scratch = "6c6a2e73-6563-6170-7368-637461726353"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"

[compat]
BenchmarkTools = "1.0"
Colors = "0.12"
CoordinateTransformations = "0.6"
GeometryBasics = "0.3"
JLD2 = "0.4"
MeshCat = "0.13 - 0.14"
Parameters = "0.12"
Rotations = "1.0.2 - 1.0.2"
Scratch = "1.0"
Symbolics = "0.1.29 - 0.1.29"
julia = "1.6"
